### ISSUE TITLE
Download method docs not clear

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/device-agent#154]
### Description

https://flowforge.com/docs/device-agent/register/#download-method

Whilst these docs hint that there is an available Web UI, and that you can use it to download your yml, there is little info on how to actually do this. No detail on how to access the UI via the command (it should _at least_ link to an example).

A screenshot of the UI would also be beneficial here to provide more info/context on the advantage of using the UI method.

**Comment by Steve-Mcl** [comment]
@joepavitt is this still relevant in light of the [quick start](https://flowfuse.com/docs/device-agent/quickstart/) article (it is explicitly about the web-ui and has screenshots)?
