### ISSUE TITLE
Device agent hangs if Node-RED doesn't exit on SIGINT

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/device-agent#206]
### Current Behavior

When the device agent asks the NR instance to shutdown it does so by sending a SIGINT.

If there is a bad node that blocks shutdown we need to be able to forcefully kill the NR process so we can start a new snapshot

### Expected Behavior

After a suitable timeout the NR process should be sent a SIGKILL to the process

### Environment

- FlowFuse version: 1.13.3
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: Linux
- Browser: na

**Comment by Steve-Mcl** [comment]
@hardillb Should we close this in light of #227 / #236?

**Comment by hardillb** [comment]
Yes
