### ISSUE TITLE
Use of console.log in Function node can break device log streaming

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/device-agent#218]
### Current Behavior

A Function node can use console.log to write directly to stdout. This can break the log parsing to stops logs being streamed to the platform.

### Expected Behavior

console.log not to break the logs

### Steps To Reproduce

Add console.log to a Function node running on a device

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by hardillb** [comment]
This is specifically console.log outputing a JSON object, a normal string works fine

**Comment by hardillb** [comment]
Problem is here:

https://github.com/FlowFuse/device-agent/blob/be492a783f267062aa7ce25641ef34c12983506e/lib/logging/log.js#L20-L26

Where we just try and JSON parse the line (as we are using the custom logger plug in to output JSON), so we need to check if the input is actually from the NR logger or from something else.

**Comment by Steve-Mcl** [comment]
Verified from local device to staging



![Image](https://github.com/FlowFuse/device-agent/assets/44235289/49deb2ec-cfd4-4ec9-ac6c-22966f1ca18c)



![Image](https://github.com/FlowFuse/device-agent/assets/44235289/84668567-bed3-4354-bcbb-b10c8511ec56)
