### ISSUE TITLE
Add heartbeat to editor tunnel websocket

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/device-agent#288]
### Description

If the device editor has the editor tunnel connected, but there is no active editor open, the websocket goes idle and gets disconnected by the platform regularly. This fills the logs with connection closed/reconnecting log messages - which can make the platform appear unstable to the user.

It would be better to have a heartbeat keeping the connection alive.

Will need to be done in a way that doesn't upset the platform when this new heartbeat packet arrives from an updated device agent.

**Comment by hardillb** [comment]
@knolleary how did you get the editor tunnel to connect, but not have an open editor?

Do you need to open a editor then close it?
