### ISSUE TITLE
Update MQTT.js to latest

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/device-agent#321]
### Description

As it stands, main branch package refers to v5.9.1

5.10.1 is now current, has many more downloads in the NPM stats that the 5.9.1 we have in the un tagged main branch

Perhaps worth an update before 2.10 release?

**Comment by Steve-Mcl** [comment]
@hardillb - for your consideration

**Comment by hardillb** [comment]
I don't see why not, the comments on the release notes look good.
